### ISSUE TITLE
is the browser required to start the ServiceWorker for postMessage() if there is no message event handler?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1200]
Consider this code:

```
// main window script
let bc = new BroadcastChannel('sw_side_channel');
sw.onmessage = evt => console.log('service worker started up');
navigator.serviceWorker.controller.postMessage('ping');

// service worker script
let bc = new BroadcastChannel('sw_side_channel');
bc.postMessage('pong');
self.onmessage = null;  // no direct message event handler
```

Is the browser required to start the service worker if its not running and a postMessage() is fired at while there is no message event handler?  Worker startup is observable thanks to things like BroadcastChannel or Clients API.

Or can the browser do similar optimizations like we do for FetchEvent where we don't start the worker if there is no message handler?

**Comment by jakearchibald** [comment]
I think we should do it for all events.

https://w3c.github.io/ServiceWorker/#handle-functional-event-algorithm covers it for "functional events", but "message" isn't one of those. We should be consistent here.

**Comment by wanderview** [comment]
Hmm, I didn't realize this mechanism had been expanded beyond FetchEvent.  Does chrome do this for other events yet?

**Comment by jakearchibald** [comment]
Not sure about implementation. I'm looking at changing that functional event algorithm btw, but not that particular behaviour https://github.com/w3c/ServiceWorker/pull/1199

**Comment by wanderview** [comment]
I just thought making event handlers observable at all was contentious so we limited it to fetch.

**Comment by jakearchibald** [comment]
I don't have strong feelings here. Happy to make it just fetch.

**Comment by mattto** [comment]
Chrome just does the optimization for fetch currently.

**Comment by jakearchibald** [comment]
Action: We should make this behaviour optional in the spec, but allow it for any top level event, including `message`.

**Comment by jakearchibald** [comment]
Action: As before. Make it a *may*.

**Comment by mattto** [comment]
Addressed in https://github.com/w3c/ServiceWorker/pull/1417

**Comment by mattto** [comment]
At https://github.com/whatwg/dom/pull/653 @annevk argues it should be limited to fetch or should be a _must_ rather than a _may_.

**Comment by yoshisatoyanagisawa** [comment]
https://w3c.github.io/ServiceWorker/#should-skip-event may work?

**Comment by yoshisatoyanagisawa** [comment]
Then, may be addressed by https://github.com/w3c/ServiceWorker/pull/1417 ?

**Comment by monica-ch** [comment]
[Bug triage] Issue still exists https://github.com/w3c/ServiceWorker/issues/1200#issuecomment-549719690,  update spec with warning or something when we skip event
